trigger:

- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'b0cf3d2f-716a-46f6-ad18-f38a066e9863'
  imageRepository: 'urlscraper'
  containerRegistry: 'shoppinghelper.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/ShoppingHelper/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Helm
  displayName: Add Helm Repo
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo helm repo add dabma https://helm.danielbjerre.net/'

- stage: Prod
  displayName: Deploy Prod
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Visual Studio Enterprise-abonnement – MPN (50fc8cf7-a304-429a-8a1c-a39bc2e915d1)'
        azureResourceGroup: 'rg-shoppinghelper-prod'
        kubernetesCluster: 'aks-shoppinghelper-prod'
        command: 'install'
        chartType: 'Name'
        chartName: 'dabma/worker'
        releaseName: 'urlscraper'